### ISSUE TITLE
Keys bound using :hydra do not use specified keyword pairs

### ISSUE THREAD

**Issue by hgersen** [Kungsgeten/ryo-modal#14]
When binding keys with :hydra to create keybindings it does not apply any of the keyword pairs to the bound key. 

Most of these keyword pairs might be less relevant for a hydra, but still the :mode would be useful. In particular to be able to reuse the same key, but bound to different hydras, depending on the major mode. 

btw) this looks like an easy fix for just the :mode, but it might be that it is intended to also work for the other keyword pairs?

**Comment by Kungsgeten** [comment]
The initial intention was that `:hydra` shouldn't use the keyword pairs, probably because that was easier to code :) I see your point though, that the `:mode` keyword can be useful, but perhaps not the others (maybe `:name`). I've now changed so that keywords will work with hydras. Hopefully it won't break anything :D
