### ISSUE TITLE
Error (use-package): ryo-modal/:config: Invalid function: nil

### ISSUE THREAD

**Issue by jpuerj** [Kungsgeten/ryo-modal#20]
Thanks for the package, I found it to be the best of it's kind. I'm getting this error when I start Emacs and I couldn't solve it yet. I'm using the same piece of code I was using before formatting my computer, so it's very wierd. Here is my .emacs:

[emacs.txt](https://github.com/Kungsgeten/ryo-modal/files/1854283/emacs.txt)

Appreciate any help, I need to make some documents in auctex. Excuses any mistake in the form of the post, I don't have a lot of experience in Git.

**Comment by Kungsgeten** [comment]
The problem is this line:

`("c" copy-line)`

There's no function with the name `copy-line`, so `ryo-modal` fails when trying to get the documentation for it. I've added a commit so that these errors will be clearer. With this commit you would have gotten this error message instead:

`Error (use-package): ryo-modal/:config: ‘copy-line’ isn’t a function`
