### ISSUE TITLE
Ryo doesn't play well with multiple-cursors

### ISSUE THREAD

**Issue by rsuhada** [Kungsgeten/ryo-modal#8]
If I'm in ryo mode I can't seem to use multiple-cursors correctly. 
All ryo: prefixed commands simply collapse the cursors into the first one and quit mutliple cursors...

Example:
I have `ryo:forward-word` in the `mc/cmds-to-run-for-all`, but activating it just quits my multi cursor selection.

Do you by any chance know how to fix this? 
Thank you very much!

**Comment by Kungsgeten** [comment]
This seems similar to issue #2. I'm not sure how to fix it, but hopefully I'll have some time to look into it.

**Comment by Kungsgeten** [comment]
The latest commit changes how `ryo` creates bindings. They are now defined as commands, just like every other command in Emacs. This has both pros and cons. The main con is that it clutters the command namespace, and that the commands get ugly names (since they need to have unique names). The biggest pro is that Ryo now works with `multiple-cursors`!
